### ISSUE TITLE
Why do HTML documents generated with qdoc turn QString into int？

### ISSUE THREAD

**Issue by xinchangli** [fpoussin/QtUsb#25]
//.h
![微信截图_20190401231651](https://user-images.githubusercontent.com/39940189/55338968-56593e80-54d4-11e9-824a-1ab3d0c8605b.png)

//cpp
![微信截图_20190401231632](https://user-images.githubusercontent.com/39940189/55339013-725ce000-54d4-11e9-8101-a5fecca53fdf.png)

//.qdocconf
![微信截图_20190401231910](https://user-images.githubusercontent.com/39940189/55339096-98828000-54d4-11e9-841f-b337fdcb52b8.png)

html file
![微信截图_20190401230807](https://user-images.githubusercontent.com/39940189/55338814-0a0dfe80-54d4-11e9-9835-c00bff8a8934.png)

run with cmd
![微信截图_20190401232222](https://user-images.githubusercontent.com/39940189/55339361-1777b880-54d5-11e9-9898-64ba8944fa5b.png)

**Comment by fpoussin** [comment]
Hi,
I'm not sure how this is related to QtUsb, could you explain?

Thanks

**Comment by xinchangli** [comment]
sorry,wrong place @fpoussin
