### ISSUE TITLE
Android build

### ISSUE THREAD

**Issue by gaminn** [fpoussin/QtUsb#30]
Hi,
will QtUsb work on Android to read generic HID USB device?

Are there any instruction how to build this library for crosscompiling on Windows host for Android armv7 device, Qt 5.11.2?

**Comment by fpoussin** [comment]
Hi,

I've never tested it on Android.
You should be able to cross compile it using the Qt SDK for android.

**Comment by tranvinhphuc111996** [comment]
Hi, i need this lib for android. i cant build this module for android_armv7

**Comment by fpoussin** [comment]
I can't help you if you don't give me any information.

**Comment by fpoussin** [comment]
I've added experimental support, it now builds and can be used like other platforms.
You will need to initialize the libusb submodule.
Untested.

**Comment by tranvinhphuc111996** [comment]
/home/phuc/Desktop/UsbHid/QtUsb/QtUsb/src/usb/qusbinfo_p.h:9:31: fatal error: libusb-1.0/libusb.h: No such file or directory
 #include <libusb-1.0/libusb.h>
!!! Hi !!! i found this error when i make build

**Comment by tranvinhphuc111996** [comment]
Oh i was built .

**Comment by HKH13** [comment]
Hi, can i guide me on how can I install qusb?
because I can not install it on linux as guide you wrote
