### ISSUE TITLE
#include install issue when using downloaded zip

### ISSUE THREAD

**Issue by jhihn** [fpoussin/QtUsb#38]
I don't know if this is an issue with QtUsb code or not, but when the master branch is downloaded as a zip, the headers fail to be be installed correctly.

The zip calls the dir QtUsb-master.zip, which on OSX extracts to QtUsb-master/
Then when compiling a dependent project the #includes for the QtUsb classes fail.

When using `git clone` to clone the repo on the same machine and a sibling directory, everything "just works".

**Comment by fpoussin** [comment]
This is normal, it depends on the libusb submodule.
