### ISSUE TITLE
SetupDiEnumDeviceInfo  bad api

### ISSUE THREAD

**Issue by linminglu** [fpoussin/QtUsb#4]
SetupDiEnumDeviceInfo Can not get the deivice on usb type

**Comment by fpoussin** [comment]
Can you be more specific?
Any test case?

Thanks

**Comment by kangqf** [comment]
right i get the same problem,the  SetupDiEnumDeviceInfo always return "ERROR_NO_MORE_ITEMS 259 (0x103) No more data is available."  for all devices

**Comment by kangqf** [comment]
oh i'm so sorry, i use the ClassGuid but DeviceGUID,so it couldn't open the devices.

**Comment by linminglu** [comment]
In this function   the  winusb_initializen . return 0 !!!
    PWINUSB_INTERFACE_HANDLE tempHandlePtr = phWinUSBHandle;
    if(!WinUsb_Initialize(hDeviceHandle, tempHandlePtr))
    {
        printUsbError("WinUsb_Initialize");

**Comment by linminglu** [comment]
and getlasterror is 0

**Comment by fpoussin** [comment]
Check the function doc here:
https://msdn.microsoft.com/fr-fr/library/windows/hardware/ff540277(v=vs.85).aspx

Are you sure the interface is not already claimed by a driver or application?

**Comment by fpoussin** [comment]
No updates - closing
