### ISSUE TITLE
Map SerialPort::portName to QUsbDevice::Id::port for devices that use serial communication (like arduino)

### ISSUE THREAD

**Issue by tiedown-maamir** [fpoussin/QtUsb#44]
Hey Fabien!

First off, thank you so much for this library - it's really well written and useful. I'd love a feature for this library. I'll just use an example to explain my feature request:

Say I have a USB hub with four _identical_ devices connected to it: 

____|_____
| port 1 | <-> COM3
| port 2 | <-> COM14
| port 3 | <-> COM15
| port 4 | <-> COM12
|________|

(These COM numbers will change depending on the order in which they're connected)

It would be awesome to know which SerialPort::portName corresponds to which QUsbDevice::Id::port. 

As far as I can tell, this is non-trivial on Windows. On windows, Qt uses these registry entries to extract serial port names.
 
![image](https://user-images.githubusercontent.com/60615748/76031587-fbab3c80-5f05-11ea-9418-ec07e68c43b1.png)

**Comment by fpoussin** [comment]
Hello,

I've added an example for listing devices.
If the serial port driver claims the usb interface, you won't be able to do anything with it, so it won't be in the list.

**Comment by fpoussin** [comment]
As for extracting Serial port names, this is out of the scope of QtUsb, it entirely depends on the operating system.

**Comment by tiedown-maamir** [comment]
Thanks for the example. I figured it would be out-of-scope, but you only know if you try ;)

![image](https://user-images.githubusercontent.com/60615748/76092495-7c614b80-5f8d-11ea-8aa3-9f72c7c5b8b5.png)

I looked at the source for Qt's serial port library and I don't think it's possible to get a GUID, or hardware location of COM ports without using WinApi. Time for more digging :)
