### ISSUE TITLE
OSX: Project ERROR: Could not find hidapi-libusb using PKGCONFIG

### ISSUE THREAD

**Issue by jhihn** [fpoussin/QtUsb#48]
**Describe the bug**
When doing a make, I get
Project ERROR: Could not find hidapi-libusb using PKGCONFIG
However hidapi and libusb are installed. There is no brew formula for hidapi-libusb

**PLatform:**
 - OS: MacOS
 - Version:Catalina

**To Reproduce**
git clone https://github.com/fpoussin/QtUsb.git
cd QtUsb
mkdir build && cd build
make

**Expected behavior**
It shoudl compile

**Additional context**
It fails with 
Project MESSAGE: Build as Qt module
Project ERROR: Could not find hidapi-libusb using PKGCONFIG
make[1]: *** [sub-usb-make_first] Error 3
make: *** [sub-src-make_first] Error 2

**Comment by fpoussin** [comment]
Can you list installed lib packages with ```pkg-config --list-all```?

You can try to edit https://github.com/fpoussin/QtUsb/blob/master/src/usb/files.pri#L110 to change *hidapi-libusb* to *hidapi*

**Comment by jhihn** [comment]
That seems to have fixed it! Thanks!
