### ISSUE TITLE
QT modules usb not found

### ISSUE THREAD

**Issue by joejond** [fpoussin/QtUsb#50]
I'm using ubuntu 18.04, and want to try using Qt USB by adding repo to my ubuntu.
I'm succeed install in my pc using apt install libqt5usb5 and libqt5usb5-dev.

after install I want to try this module to my QT  (qt5.9), unfortunately this error come up. 
"Unknown module(s) in QT: usb"

How to check in my pc, is my  module installed correctly?

**Comment by fpoussin** [comment]
I haven't updated the packages to the latest version, but it should still work.
Are you using the system Qt version and not an official package?

**Comment by fpoussin** [comment]
I've updated the packages to the latest release

**Comment by joejond** [comment]
Thanks for your update.. currently I using include in project .pro file, and its working.
If you update with newer version, I will try again using apt install. 

Is there any sample creating protocol using pc host and device using usb?

Verywell thanks

**Comment by fpoussin** [comment]
As I said, package have been updated, you can retry.

There are no examples of protocols as it's out of the scope of QtUsb.
You can have a look at modbus: https://doc.qt.io/qt-5/qtmodbus-backends.html

**Comment by selmehtar** [comment]
I have the same issue using Windows. I added the library to my project and added QT += usb to the .pro file and get the error "Project ERROR: Unknown module(s) in QT: usb".

**Comment by fpoussin** [comment]
This is normal, please read the instructions
