### ISSUE TITLE
enum bmRequestType values are not shifted properly

### ISSUE THREAD

**Issue by digitalaspirin** [fpoussin/QtUsb#56]
The values for bmRequestType enum are not properly initialized:

requestStandard = (0x00 < 5),
requestClass = (0x01 < 5),
requestVendor = (0x02 < 5),
requestReserved = (0x03 < 5), 

**The values should be:**
requestStandard = (0x00 << 5),
requestClass = (0x01 << 5),
requestVendor = (0x02 << 5),
requestReserved = (0x03 << 5),

**Comment by fpoussin** [comment]
Thanks for finding this
