### ISSUE TITLE
Register QUsbDevice::DeviceStatus

### ISSUE THREAD

**Issue by digitalaspirin** [fpoussin/QtUsb#57]
Hello,
I think it will be rather better if QUsbDevice class registers QUsbDevice::DeviceStatus enum, using qRegisterMetaType() instead of having to do it at the application level when trying to connect statusChanged signal to handle a USB error.

```
qRegisterMetaType<QUsbDevice::DeviceStatus>("QUsbDevice::DeviceStatus"); // Needed so that the following connection does not fail at run time.
connect(m_usb_dev,&QUsbDevice::statusChanged,this,[](QUsbDevice::DeviceStatus status) {
    qDebug () << "USB ERROR: " << qint32(status) << " deal with it";
});

**Comment by fpoussin** [comment]
Good catch, this has been fixed.
Thanks!
