### ISSUE TITLE
getAvailableDevices() returns empty list.

### ISSUE THREAD

**Issue by tswindell** [fpoussin/QtUsb#6]
I'm presuming I'm doing something wrong, but why do I get no results from this:

    #include <QCoreApplication>
    #include <QUsb>

    int main(int argc, char *argv[])
    {
        QCoreApplication a(argc, argv);
        QUsbManager devices;

        QtUsb::FilterList list = devices.getPresentDevices();
        foreach(QtUsb::DeviceFilter filter, list)
        {
            qDebug("%04x:%04x", filter.vid, filter.pid);
        }

        return a.exec();
    }

**Comment by fpoussin** [comment]
Which platform are you on?

**Comment by tswindell** [comment]
Windows 10

**Comment by fpoussin** [comment]
Are you sure you have unclaimed WinUSB devices available?

**Comment by tswindell** [comment]
Well, the device shows up when it's plugged in through the deviceInserted signal. It's a HID device, which should be unrecognised by the system. But I guess HID devices can be automatically grabbed by Windows?

**Comment by tswindell** [comment]
It's actually a composite device, it exposes some HID interfaces which seem to be recognised by the HID subsystem in Windows. Though it also has 3 unrecognised devices.

**Comment by fpoussin** [comment]
I think I found the issue, I'll let you know.

**Comment by tswindell** [comment]
Ok, so I just noticed QUsbDevice::getAvailableDevices(), which returns what I need. It seems that QUsbManager is actually a QThread so maybe it isn't populated immediately like my example expected.

**Comment by fpoussin** [comment]
Yes, getPresentDevices() does not populates from the start, that's the problem.

**Comment by fpoussin** [comment]
So the documentation is a bit misleading, getPresentDevices() actually returns devices that are present in the system AND in the list. You have to use addDevice() to add these to the list.
It's meant to only return devices that you are interested in.

**Comment by tswindell** [comment]
Okay, that's fine. :)

**Comment by fpoussin** [comment]
Feel free to close the ticket.
I'll update the documentation.
