### ISSUE TITLE
hid_enumerate(0x0,0x0) vs QUsbInfo::devices()

### ISSUE THREAD

**Issue by Jihadist** [fpoussin/QtUsb#61]
Hello, i see you use libusb_get_device_list() in QUsbInfo::devices(). But this way i couldnt find my hid while hid_enumerate could. Is there an additonal way to find hid? Thanx

P.s. QHidDevice:open still works for this device while QUsbInfo::devices() could find it

**Comment by fpoussin** [comment]
This is normal, you can't interact with USB devices which use the HID driver, since they are already claimed by it.

**Comment by fpoussin** [comment]
I'll find a way to add these to the list
