### ISSUE TITLE
How to read or write file?

### ISSUE THREAD

**Issue by Wzshun** [fpoussin/QtUsb#63]
I want to read or write a text file with usb device.
The bluk example, I don't understand where is it send data to.

Or how to get a QFile from UsbDevice?

**Comment by fpoussin** [comment]
Hi,

The example uses an _array_ with some data that is written to an _endpoint_ (a kind of one-way pipe).
You can use a _QFile_ to write directly to an endpoint, they both inherit the _QIODevice_ abstract class.
Something like _QFile >> QUsbEndpoint_ (using streams) should work.
Or you can simply read from a file then write to an endpoint.

I suggest you read about USB to understand how to achieve your goal:
https://www.beyondlogic.org/usbnutshell/usb1.shtml
https://fpoussin.github.io/doxygen/qtusb/0.6.x/
