### ISSUE TITLE
got  fatal error: qusbglobal.h: No such file or directory

### ISSUE THREAD

**Issue by allenlorenz** [fpoussin/QtUsb#65]
Ubuntu 20.04 

did the following install from the Readme

sudo add-apt-repository ppa:fpoussin/ppa
sudo apt install libqt5usb5 libqt5usb5-dev

compile a file with include  file \<QusbDevice\>   

ex ListDevices from example directory

**Comment by viniciusbenite** [comment]
Same on 18.04.

**Comment by allenlorenz** [comment]
Found the answer there was a missing qt package.

sudo apt-get install qtbase5-private-dev

I do think this should be noted in the readme.  While it might depend on distribution, Qt evolutionary changes of what packages have what can confuse anyone at times.
