### ISSUE TITLE
Crash in QUsb Constructor

### ISSUE THREAD

**Issue by ra4444** [fpoussin/QtUsb#66]
**Describe the bug**
Created and ran a program that called the QUsb constructor.  The program started consuming large amounts of memory and then crashed.

**PLatform:**
 - OS: Windows
 - Version: 10

**To Reproduce**
1. Build the following program:
```c++
#include <QCoreApplication>
#include <QUsb>

int main(int argc, char *argv[])
{
    QCoreApplication app(argc, argv);
    QUsb usb;
    return app.exec();
}
```
2. Run the program.

**Expected behavior**
No crash.

**Additional context**
The problem appears to be in `QUsb::devices()` in the while loop that traverses the linked list of HID devices.  In particular, this line in the while loop:
```c++
    cur_hid_dev = hid_devs->next;
```
should be this:
```c++
    cur_hid_dev = cur_hid_dev->next;
```

**Comment by fpoussin** [comment]
Thank you!
