### ISSUE TITLE
Avoid keyword 'interface' in QUsb::Config

### ISSUE THREAD

**Issue by gilgm12** [fpoussin/QtUsb#68]
Triggers compiler error C2236.

The offending classmember is here:
qusb.h:39

When including windows headers, the identifier name "interface" breaks the build.  Swapping the classmember to 'usb_interface' to correct this issue, although I'm not sure that identifier is best or what that particular data member represents. (usb IF was an assumption)

`
        quint8 usb_interface;
`

**Platform:**
 - OS: Windows
 - Version 10 19042

**Comment by gilgm12** [comment]
Optional Patch:
[usb_interface.txt](https://github.com/fpoussin/QtUsb/files/5593106/usb_interface.txt)

**Comment by hua52841422** [comment]
INCLUDEPATH += $$PWD/../deps/msvc $$LIBUSB_ROOT_REL $$LIBUSB_ROOT_REL/libusb $$HIDAPI_ROOT_REL $$HIDAPI_ROOT_REL/hidapi  MSVC编译出错

**Comment by fpoussin** [comment]
I've had this problem a while ago, I'll need to undefine "interface"

**Comment by fpoussin** [comment]
Can you try again?

**Comment by gilgm12** [comment]
Yessir - I'll give it a go.  I'm in the middle of a few other adjustments also - is there a good way to connect with you via chat?

**Comment by fpoussin** [comment]
Not really, here is fine.
Did you have a chance to retry?

**Comment by fpoussin** [comment]
Any update?
