### ISSUE TITLE
events_windows.c and windows_common.c missing

### ISSUE THREAD

**Issue by neomissing** [fpoussin/QtUsb#69]
events_windows.c and windows_common is not exist,Failed to compile

**Comment by fpoussin** [comment]
Works fine in CI. You a probably doing something wrong.

**Comment by neomissing** [comment]
I am download the code from the git directly, directly in the source code to compile and file the lack of reason to find, source specified libusb data source is not your own libusb data sources, so there is libusb content is not unified, but I changed your own libusb data source, find or cannot be compiled, is directly with hid the demo and I use compile the source code, a pile of warning, not compile in the past, the early version is also not the problem, can also be modified to support mingw compilation, new update with qt call MSVC compilers are not?I want to see where it doesn't match



neomissing@163.com
 
From: Fabien Poussin
Date: 2020-12-16 20:26
To: fpoussin/QtUsb
CC: neomissing; Author
Subject: Re: [fpoussin/QtUsb] events_windows.c and windows_common.c missing (#69)
Works fine in CI. You a probably doing something wrong.

**Comment by fpoussin** [comment]
Did you try using the msvc build script?

**Comment by neomissing** [comment]
[QtUsb_Hiddemo.zip](https://github.com/fpoussin/QtUsb/files/5702916/QtUsb_Hiddemo.zip)
Attached is my test demo using QT MSVC2019

**Comment by fpoussin** [comment]
I cannot check your file now as I'm on my phone. Make sure you initialize the git submodules and use the build script without any modifications. It should work fine. You can also use one of the releases. I can't help you if you change the libusb sources.

**Comment by neomissing** [comment]
libusb for libusb source is different with your libusb source，you can compare，events_windows.c is remove，windows_common.c change to windows_nt_common.c，your own libusb source not the same

发自我的iPhone

**Comment by neomissing** [comment]
libusb for libusb source is different with your libusb source，you can compare，events_windows.c is remove，windows_common.c change to windows_nt_common.c，your own libusb source not the same

发自我的iPhone

**Comment by fpoussin** [comment]
Yes, this is intended and normal.

**Comment by neomissing** [comment]
> Yes, this is intended and normal.

so，the demo is not change anything，but can bulid，if you have time，can test it，think you

**Comment by neomissing** [comment]
I use the latest program, recompile, still cannot compile the compiler in the past, a lot of errors, can you give me a normal demo of the compilation，
![QQ截图20201217101931](https://user-images.githubusercontent.com/22003930/102435375-7686b380-4051-11eb-85b2-efdd652fb9ea.png)
![QQ截图20201217102032](https://user-images.githubusercontent.com/22003930/102435513-b5b50480-4051-11eb-8b8b-8bcdaeeabaca.png)
![QQ截图20201217102050](https://user-images.githubusercontent.com/22003930/102435518-b77ec800-4051-11eb-8916-4a3494ec9064.png)
![QQ截图20201217102129](https://user-images.githubusercontent.com/22003930/102435519-b8175e80-4051-11eb-8e02-6d1e596126e0.png)
![QQ截图20201217102153](https://user-images.githubusercontent.com/22003930/102435522-b8175e80-4051-11eb-9464-c52554daf145.png)

**Comment by neomissing** [comment]
I have seen git in CI work is wrong, and the wrong phenomenon is the same as mine. You can check what is wrong, thank you

**Comment by fpoussin** [comment]
Yes, I updated the libusb submodule and will update project files. Again, this is normal.

**Comment by fpoussin** [comment]
Fixed

**Comment by neomissing** [comment]
Hello, there are still two bug points modified, such as change,(1)qusb.h line 6 add #include <QObject>,(2)qusb.cpp line 4 add #include "qdebug.h" after modification to support qt MSVC compilation


neomissing@163.com
 
From: Fabien Poussin
Date: 2020-12-17 23:01
To: fpoussin/QtUsb
CC: neomissing; Author
Subject: Re: [fpoussin/QtUsb] events_windows.c and windows_common.c missing (#69)
Fixed

**Comment by neomissing** [comment]
There is also a problem with the signals being sent repeatedly. For example, in the UsbNotifications demo, plug and pull USB will trigger two plug and two pull signals



neomissing@163.com
 
From: neomissing@163.com
Date: 2020-12-18 12:24
To: fpoussin/QtUsb
Subject: Re: Re: [fpoussin/QtUsb] events_windows.c and windows_common.c missing (#69)

Hello, there are still two bug points modified, such as change,(1)qusb.h line 6 add #include <QObject>,(2)qusb.cpp line 4 add #include "qdebug.h" after modification to support qt MSVC compilation


neomissing@163.com
 
From: Fabien Poussin
Date: 2020-12-17 23:01
To: fpoussin/QtUsb
CC: neomissing; Author
Subject: Re: [fpoussin/QtUsb] events_windows.c and windows_common.c missing (#69)
Fixed
