### ISSUE TITLE
QUsbInfo missing?

### ISSUE THREAD

**Issue by ua-fl** [fpoussin/QtUsb#70]
I'm trying to compile an existing project on a new machine(Ubuntu, 20.04).
But Qt complains about a non-existing "QUsbInfo" include file.
And it is right, I also cannot find it. 
I'm relatively sure that my project worked before and your documentation also tells about QUsbInfo(https://fpoussin.github.io/doxygen/qtusb/0.6.x/qusbinfo.html#details). But I cannot see it in ../src/usb.
Was it renamed, moved or has it disappeared?

Cheers,
Uwe

**Comment by fpoussin** [comment]
Hi,
Yes it was was move to QUsb with some other parts.
I assume you we previously using another release, so this is normal.
