### ISSUE TITLE
I can not build in Windows

### ISSUE THREAD

**Issue by ehrenmann1977** [fpoussin/QtUsb#73]
**Describe the bug**
I downloaded the git repo and downloaded hid, lusb repos as well. Loading the QtUSB pro file and compiling does not work

**PLatform:**
win 10

**To Reproduce**
download repo and other repos and try to compile on a fresh win 10 system

**Expected behavior**

**Additional context**

D_UNICODE -DWIN32 -DMINGW_HAS_SECURE_API=1 -DWINVER=0x0601 -D_WIN32_WINNT=0x0601 -DQT_NO_LINKED_LIST -DQT_BUILD_USB_LIB -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_BUILD_USB_LIB -DQT_BUILDING_QT -D_CRT_SECURE_NO_WARNINGS -D_USE_MATH_DEFINES -DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x040800 -DQT_DEPRECATED_WARNINGS_SINCE=0x060000 -DQT_NO_EXCEPTIONS -DQT_NO_DEBUG -DQT_CORE_LIB -IC:\Users\SHERIF\Desktop\USBProject\QtUsb\src\usb -I. -IC:\Users\SHERIF\Desktop\USBProject\QtUsb\src\usb -IC:\Users\SHERIF\Desktop\USBProject\QtUsb\src\deps\msvc -IC:\Users\SHERIF\Desktop\USBProject\QtUsb\libusb -IC:\Users\SHERIF\Desktop\USBProject\QtUsb\libusb\libusb -IC:\Users\SHERIF\Desktop\USBProject\QtUsb\hidapi -IC:/Users/SHERIF/Desktop/USBProject/QtUsb/src/usb/../../hidapi/hidapi -I..\..\include -I..\..\include\QtUsb -I..\..\include\QtUsb\0.7.0 -I..\..\include\QtUsb\0.7.0\QtUsb -Itmp -ID:\Qt\5.15.2\mingw81_64\include\QtCore\5.15.2 -ID:\Qt\5.15.2\mingw81_64\include\QtCore\5.15.2\QtCore -ID:\Qt\5.15.2\mingw81_64\include -ID:\Qt\5.15.2\mingw81_64\include\QtCore -I.moc\release -IC:\openssl\include -IC:\Utils\my_sql\mysql-5.7.25-winx64\include -IC:\Utils\postgresql\pgsql\include -ID:\Qt\5.15.2\mingw81_64\mkspecs\win32-g++  -o .obj\release\qusbendpoint.o C:\Users\SHERIF\Desktop\USBProject\QtUsb\src\usb\qusbendpoint.cpp
In file included from C:\Users\SHERIF\Desktop\USBProject\QtUsb\src\usb\qusb.cpp:2:
C:\Users\SHERIF\Desktop\USBProject\QtUsb\src\usb\qusb_p.h:13:12: fatal error: hidapi/hidapi.h: No such file or directory
   #include <hidapi/hidapi.h>
            ^~~~~~~~~~~~~~~~~
compilation terminated.
mingw32-make[3]: *** [Makefile.Release:584: .obj/release/qusb.o] Error 1
mingw32-make[3]: *** Waiting for unfinished jobs....
In file included from C:\Users\SHERIF\Desktop\USBProject\QtUsb\src\usb\qusbdevice.h:5,
                 from C:\Users\SHERIF\Desktop\USBProject\QtUsb\src\usb\qusbendpoint.h:4,
                 from C:\Users\SHERIF\Desktop\USBProject\QtUsb\src\usb\qusbendpoint_p.h:4,
                 from C:\Users\SHERIF\Desktop\USBProject\QtUsb\src\usb\qusbendpoint.cpp:1:
C:\Users\SHERIF\Desktop\USBProject\QtUsb\src\usb\qusb.h:17:1: error: expected class-name before '{' token
 {
 ^
C:\Users\SHERIF\Desktop\USBProject\QtUsb\src\usb\qusb.h:18:5: error: 'Q_OBJECT' does not name a type
     Q_OBJECT
     ^~~~~~~~
C:\Users\SHERIF\Desktop\USBProject\QtUsb\src\usb\qusb.h:18:5: note: the macro 'Q_OBJECT' had not yet been defined
In file included from D:\Qt\5.15.2\mingw81_64\include/QtCore/qobject.h:46,
                 from D:\Qt\5.15.2\mingw81_64\include/QtCore/qiodevice.h:45,
                 from D:\Qt\5.15.2\mingw81_64\include/QtCore/qtextstream.h:43,
                 from D:\Qt\5.15.2\mingw81_64\include\QtCore/qdebug.h:49,
                 from D:\Qt\5.15.2\mingw81_64\include\QtCore/QDebug:1,
                 from C:\Users\SHERIF\Desktop\USBProject\QtUsb\src\usb\qusbdevice.h:7,
                 from C:\Users\SHERIF\Desktop\USBProject\QtUsb\src\usb\qusbendpoint.h:4,
                 from C:\Users\SHERIF\Desktop\USBProject\QtUsb\src\usb\qusbendpoint_p.h:4,
                 from C:\Users\SHERIF\Desktop\USBProject\QtUsb\src\usb\qusbendpoint.cpp:1:
D:\Qt\5.15.2\mingw81_64\include/QtCore/qobjectdefs.h:170: note: it was later defined here
 #define Q_OBJECT \
 
In file included from C:\Users\SHERIF\Desktop\USBProject\QtUsb\src\usb\qusbdevice.h:5,
                 from C:\Users\SHERIF\Desktop\USBProject\QtUsb\src\usb\qusbendpoint.h:4,
                 from C:\Users\SHERIF\Desktop\USBProject\QtUsb\src\usb\qusbendpoint_p.h:4,
                 from C:\Users\SHERIF\Desktop\USBProject\QtUsb\src\usb\qusbendpoint.cpp:1:
C:\Users\SHERIF\Desktop\USBProject\QtUsb\src\usb\qusb.h:19:1: error: expected '}' before end of line
     Q_DECLARE_PRIVATE(QUsb)
 ^   ~~~~~~~
C:\Users\SHERIF\Desktop\USBProject\QtUsb\src\usb\qusb.h:17:1: note: to match this '{'
 {
 ^
C:\Users\SHERIF\Desktop\USBProject\QtUsb\src\usb\qusb.h:19:1: error: expected unqualified-id before end of line
     Q_DECLARE_PRIVATE(QUsb)
 ^   ~~~~~~~
C:\Users\SHERIF\Desktop\USBProject\QtUsb\src\usb\qusb.h:19:1: error: expected declaration before end of line
mingw32-make[3]: *** [Makefile.Release:679: .obj/release/qusbendpoint.o] Error 1
mingw32-make[3]: Leaving directory 'C:/Users/SHERIF/Desktop/USBProject/build-QtUsb-Desktop_Qt_5_15_2_MinGW_64_bit-Release/src/usb'
mingw32-make[2]: *** [Makefile:45: release] Error 2
mingw32-make[2]: Leaving directory 'C:/Users/SHERIF/Desktop/USBProject/build-QtUsb-Desktop_Qt_5_15_2_MinGW_64_bit-Release/src/usb'
mingw32-make[1]: *** [Makefile:50: sub-usb-make_first] Error 2
mingw32-make[1]: Leaving directory 'C:/Users/SHERIF/Desktop/USBProject/build-QtUsb-Desktop_Qt_5_15_2_MinGW_64_bit-Release/src'
mingw32-make: *** [Makefile:52: sub-src-make_first] Error 2
22:47:13: The process "D:\Qt\Tools\mingw810_64\bin\mingw32-make.exe" exited with code 2.
Error while building/deploying project QtUsb (kit: Desktop Qt 5.15.2 MinGW 64-bit)
When executing step "Make"
22:47:13: Elapsed time: 00:16.

**Comment by fpoussin** [comment]
Hi,
mingw is not supported on windows (MSVC specified in the Readme file) so it might not work at all
