### ISSUE TITLE
How to use libusb in my project

### ISSUE THREAD

**Issue by geek-slt** [fpoussin/QtUsb#74]
**Describe the bug**

I saw on github that the QtUSB you made was developed based on libusb. I encountered some problems when using libusb to develop myself. I want to use libusb first and then use your QtUSB library. Could you please advise?

**PLatform:**
 - OS: windows 10 x64
 - Version  QT 5.15

**Comment by fpoussin** [comment]
Hi,
Can you give me some context?
Why do you need to use libusb first?

**Comment by geek-slt** [comment]
Thank you very much. This problem has been solved. Forgive me for not responding in time.
