### ISSUE TITLE
Ubuntu 20.04 newest version fails

### ISSUE THREAD

**Issue by bm16ton** [fpoussin/QtUsb#82]
Hello , Love the app! on my aging 20.04 install the latest sources fail to connect;

Verbose level: 3
Version: 1.3.0
222 - Warning: libpng warning: iCCP: known incorrect sRGB profile
263 - Warning: QObject::connect: No such signal QUsbInfo::deviceInserted(QtUsb::FilterList)
264 - Info: Devices list loaded.
274 - Info: 36 Device descriptions loaded.
2875 - Info: Searching Device...
2875 - Info: Found device
2876 - Info: Device Open
2876 - Info: ST Link V2 / Nucleo found!
2877 - Info: Fetching version...
2877 - Warning: QIODevice::write (QUsbEndpoint): device not open
2877 - Error: In qint32 stlinkv2::sendCommand(const QByteArray&), at src/stlinkv2.cpp:734
2877 - Warning: QIODevice::read (QUsbEndpoint): device not open
2877 - Info: Fetching mode...
2877 - Warning: QIODevice::write (QUsbEndpoint): device not open
2877 - Error: In qint32 stlinkv2::sendCommand(const QByteArray&), at src/stlinkv2.cpp:734
2877 - Warning: QIODevice::read (QUsbEndpoint): device not open
2877 - Info: Mode: Unknown
2877 - Warning: QIODevice::write (QUsbEndpoint): device not open
2877 - Error: In qint32 stlinkv2::sendCommand(const QByteArray&), at src/stlinkv2.cpp:734
2877 - Warning: QIODevice::read (QUsbEndpoint): device not open
2878 - Info: Changing mode to SWD...
2878 - Warning: QIODevice::write (QUsbEndpoint): device not open
2878 - Error: In qint32 stlinkv2::sendCommand(const QByteArray&), at src/stlinkv2.cpp:734
2878 - Warning: QIODevice::read (QUsbEndpoint): device not open
2878 - Warning: QIODevice::write (QUsbEndpoint): device not open
2878 - Error: In qint32 stlinkv2::sendCommand(const QByteArray&), at src/stlinkv2.cpp:734
2979 - Info: Fetching mode...
2980 - Warning: QIODevice::write (QUsbEndpoint): device not open
2980 - Error: In qint32 stlinkv2::sendCommand(const QByteArray&), at src/stlinkv2.cpp:734
2980 - Warning: QIODevice::read (QUsbEndpoint): device not open
2980 - Info: Mode: Unknown
2980 - Info: Fetching status...
2980 - Warning: QIODevice::write (QUsbEndpoint): device not open
2980 - Error: In qint32 stlinkv2::sendCommand(const QByteArray&), at src/stlinkv2.cpp:734
2980 - Warning: QIODevice::read (QUsbEndpoint): device not open
2980 - Info: Status: Unknown
2980 - Info: Fetching MCU Info...
2980 - Warning: QIODevice::write (QUsbEndpoint): device not open
2980 - Error: In qint32 stlinkv2::sendCommand(const QByteArray&), at src/stlinkv2.cpp:734
2980 - Warning: QIODevice::read (QUsbEndpoint): device not open
2980 - Info: CoreID: 00000000
2980 - Warning: QIODevice::write (QUsbEndpoint): device not open
2980 - Error: In qint32 stlinkv2::sendCommand(const QByteArray&), at src/stlinkv2.cpp:734
2980 - Warning: QIODevice::read (QUsbEndpoint): device not open
2981 - Error: Did not find chipID!
2981 - Info: Device not found in database!
2981 - Error: Device not found in database!
2981 - Info: Disconnecting...
2981 - Warning: QIODevice::write (QUsbEndpoint): device not open
2981 - Error: In qint32 stlinkv2::sendCommand(const QByteArray&), at src/stlinkv2.cpp:734
2981 - Warning: QIODevice::read (QUsbEndpoint): device not open
2981 - Info: Closing USB connection
2982 - Info: Disconnected.

I tried changing the QObject::connect: No such signal QUsbInfo::deviceInserted(QtUsb::FilterList) code but I just couldnt figurre it out, So checking the commits  4ea16cd0cd8b0ef450637c06bd4bce9e2c597842 was the parent of the last time that line was changed, So I checkout that (and older usb submodule) compiled and it worked, Im not sure but maybe this is because im running older 20.04? I actually see last commit was probly when 20.04 was active so I dunno.

**Comment by fpoussin** [comment]
Closing this as it's related to QSTlink2, not QtUSB.
