### ISSUE TITLE
Qtusb for PL2303   

### ISSUE THREAD

**Issue by HKH13** [fpoussin/QtUsb#84]
Dear 
i can not open pl2303 device 
can you guide me
![85db7c85-fc33-48b9-a56a-2f06bae63edd](https://user-images.githubusercontent.com/16012603/146690794-70689453-8c58-46ec-825d-d9f4a2b980d7.png)
?

**Comment by fpoussin** [comment]
Hi,
Seems like your driver already claimed the interface
