### ISSUE TITLE
how to use the QUsbEndpoint::controlEndpoint 

### ISSUE THREAD

**Issue by Alvazz** [fpoussin/QtUsb#88]
Hi fpoussin. Thank for you shared this Good project.

I want use the QUsbEndpoint::controlEndpoint way. can you give me some demo code?

thanks!

**Comment by fpoussin** [comment]
Hi,

You can use the `makeControlPacket` method to generate control packets, then write it just like a normal endpoint.
It mostly depends on the device.

**Comment by Alvazz** [comment]
![1677484781700](https://user-images.githubusercontent.com/50744096/221505954-0534e387-61fa-4f5e-af8d-529bb4f1db9f.png)

```
m_read_ep = new QUsbEndpoint(m_usb_dev,QUsbEndpoint::controlEndpoint,0);
m_read_ep->makeControlPacket(buffer,QUsbEndpoint::recipientInterface,QUsbEndpoint::requestClearFeature,0x0603, 0x0600, 0x3E00);
m_read_ep->write(buffer);
```

Should I write like this?

Then where do I receive and return the data?
